field.field.*.*.*.third_party.disable_field:
  type: mapping
  label: 'Per-field disable_field settings'
  mapping:
    add_disable:
      type: string
      label: 'Option to disable field on the content add form'
    add_roles:
      type: sequence
      label: 'Enable or disable the field for the given roles on the content add form.'
      sequence:
        type: string
        label: 'Role'
    edit_disable:
      type: string
      label: 'Option to disable field on the content edit form'
    edit_roles:
      type: sequence
      label: 'Enable or disable the field for the given roles on the content edit form.'
      sequence:
        type: string
        label: 'Role'

core.base_field_override.*.*.*.third_party.disable_field:
  type: mapping
  label: 'Per-field disable_field settings'
  mapping:
    add_disable:
      type: string
      label: 'Option to disable field on the content add form'
    add_roles:
      type: sequence
      label: 'Enable or disable the field for the given roles on the content add form.'
      sequence:
        type: string
        label: 'Role'
    edit_disable:
      type: string
      label: 'Option to disable field on the content edit form'
    edit_roles:
      type: sequence
      label: 'Enable or disable the field for the given roles on the content edit form.'
      sequence:
        type: string
        label: 'Role'
