node_clone.settings:
  type: mapping
  label: Settings
  mapping:
    node_clone_method:
      type: string
    node_clone_nodes_without_confirm:
      type: boolean
    node_clone_use_node_type_name:
      type: integer
    node_clone_menu_links:
      type: boolean
