id: d7_roleassign_settings
label: RoleAssign settings
migration_tags:
  - Drupal 7
source:
  plugin: variable
  variables:
    - roleassign_roles
process:
  roleassign_roles:
    plugin: migration
    migration: d7_user_role
    source: roleassign_roles
destination:
  plugin: config
  config_name: roleassign.settings
migration_dependencies:
  required:
    - d7_user_role
