field.field.*.*.*.third_party.unique:
  type: mapping
  label: Unique field third party settings
  mapping:
    unique:
      type: checkbox
      label: Set if field is unique or not
    per_lang:
      type: checkbox
      label: Unique per language
    use_ajax:
      type: checkbox
      label: Use ajax
    message:
      type: textarea
      label: Use ajax
