# Schema for the configuration files of the Workflow module.
workflow.settings:
  type: config_object
  label: 'Workflow settings'
  mapping:
    workflow_states_per_page:
      type: integer
      label: 'Number of workflow states per page'

workflow.workflow.*:
  type: config_entity
  label: 'Workflow settings'
  mapping:
    id:
      type: string
      label: 'ID'
    status:
      type: boolean
      label: 'Status'
    label:
      type: label
      label: 'Label'
    module:
      type: string
      label: 'Module'
    options:
      type: mapping
      label: 'Options'
      mapping:
        name_as_title:
          type: integer
          label: 'Use the workflow name as the title of the workflow form'
        fieldset:
          type: integer
          label: 'Show the form in a fieldset'
        options:
          type: string
          label: 'How to show the available states'
        schedule_timezone:
          type: integer
          label: 'Show a timezone when scheduling a transition'
        comment_log_node:
          type: integer
          label: 'Show comment on the Content edit form'
        watchdog_log:
          type: integer
          label: 'Log watchdog messages upon state change'

field.storage_settings.workflow:
  type: mapping
  label: 'Workflow settings'
  mapping:
    workflow_type:
      type: string
      label: 'Workflow'
    allowed_values:
      type: sequence
      label: 'Allowed values list'
      sequence:
        type: mapping
        label: 'Allowed value with label'
        mapping:
          value:
            type: string
            label: 'Value'
          label:
            type: label
            label: 'Label'

field.field_settings.workflow:
  type: mapping
  label: 'Workflow settings'
