workflow_notifications.workflow_notify.*:
  type: config_entity
  label: 'workflow notifications settings'
  mapping:
    id:
      type: string
      label: 'ID'
    status:
      type: boolean
      label: 'Status'
    label:
      type: string
      label: 'Label'
    wid:
      type: string
      label: 'Workflow Type'
    from_sid:
      type: string
      label: 'From State ID'
    to_sid:
      type: string
      label: 'To State ID'
    when_to_trigger:
      type: string
      label: 'When To Trigger'
    days:
      type: integer
      label: 'Days'
    roles:
      type: sequence
      label: 'User roles'
      sequence:
        type: 'string'
        label: 'Role'
    mail_ids:
      type: string
      label: 'Email IDs'
    subject:
      type: string
      label: 'Subject'
    message:
      type: text_format
      label: 'Message'
