workflow_state_config.states_config:
  path: '/admin/config/workflow/workflow/{workflow_type}/states_config'
  defaults:
    _form: '\Drupal\workflow_state_config\Form\WorkflowStateConfigForm'
    _title: 'Manage Workflow Notifications'
  requirements:
    _permission: 'content access'
