<?php

/**
 * @file
 * Module file for Bulk user registration.
 */

/**
 * Implements hook_preprocess_page().
 */
function bulk_user_registration_preprocess_page(&$variables) {
  $variables['page']['#cache']['contexts'][] = 'route';
  $urlRoute = \Drupal::routeMatch()->getRouteName();
  if (($urlRoute == 'bulk_user_registration.admin_settings')) {
    $variables['#attached']['library'][] = 'bulk_user_registration/common-styling';
  }
}
