<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\workflow\Entity\WorkflowScheduledTransition;
use Drupal\workflow\Entity\WorkflowTransitionInterface;
use Drupal\workflow_notifications\Entity\WorkflowNotification;

/**
 * Implements hook_entity_update().
 * sending on state change mail.
 */
function workflow_notifications_entity_update(EntityInterface $entity) {
  // Avoid this hook on workflow objects.
  if (\Drupal\workflow\Entity\WorkflowManager::isWorkflowEntityType($entity->getEntityTypeId())) {
    return;
  }

  foreach (_workflow_info_fields($entity) as $field_info) {
    $field_name = $field_info->getName();
    /** @var $transition WorkflowTransitionInterface */
    $transition = $entity->$field_name->__get('workflow_transition');
    if (empty($transition)) {
      continue;
    }
    // @todo: hide below code in WorkflowNotification::loadMultiple()?
    $from_sid = $transition->getFromSid();
    $to_sid = $transition->getToSid();
    $wid = $transition->getWorkflowId();
    $days = 0;

    $state_changed = ($from_sid != $to_sid);
    if (!$state_changed) {
      continue;
    }

    // Default select parameters for non-scheduled transitions.
    $trigger = 'on_state_change';
    if ($transition->isScheduled()) {
      $trigger = 'before_state_change';

      $timestamp = $transition->getTimestamp();
      if (!empty($timestamp)) {
        $date = explode('-', date('d-m-y', $timestamp));
        $current_date = explode('-', date('d-m-y', \Drupal::time()->getRequestTime()));
        if ($date[1] == $current_date[1] && $date[2] == $current_date[2]) {
          if ($date[0] > $current_date[0]) {
            $days = $date[0] - $current_date[0];
          }
        }
      }
    }
    // $todo: use $transitions as parameter, and derive $trigger from that.
    $notifications = WorkflowNotification::loadMultipleByProperties($from_sid, $to_sid, $wid, $trigger, $days);
    if (!empty($notifications)) {
      _workflow_notifications_mail_trigger($trigger, $notifications, $entity, $transition);
    }

  }
}

/**
 * Implements hook_cron().
 *
 * sending remainder mail.
 **/
function workflow_notifications_cron() {
  workflow_debug('', __FUNCTION__, __LINE__);

  $config = \Drupal::service('config.factory')->getEditable('workflow_notifications.settings');
  if (date('d', $config->get('last_run_date')) != date('d')) {
    // queue to send mail.
    // @todo: use $notifications[] = WorkflowNotification::LoadByProperties()
    $result = Drupal::entityQuery("workflow_notify")->condition('when_to_trigger', 'before_state_change', '=')->execute();
    foreach ($result as $key => $value) {
      $entity = WorkflowNotification::load($key);
      $queue = \Drupal::queue('workflow_scheduled_entity_mail');
      $queue->createItem($entity);
    }
    $config->set('last_run_date', \Drupal::time()->getRequestTime())->save();
  }
}

/**
 * Implements hook_mail_alter().
 */
function workflow_notifications_mail_alter(&$message) {
  workflow_debug('', __FUNCTION__, __LINE__);
}

/**
 * Implements hook_mail().
 */
function workflow_notifications_mail($key, &$message, $params) {
  workflow_debug('', __FUNCTION__, __LINE__);

  $options = [
    'langcode' => $message['langcode'],
  ];
  $from = Drupal::config('system.site')->get('mail');
  $message['from'] = $from;
  $message['subject'] = $params['subject'];
  $message['body'][] = $params['message'];
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
}

/**
 * Internal helper function. No hook.
 */
function _workflow_notifications_mail_trigger($trigger, $notifications, $entity, $transition) {
  if (empty($notifications)) {
    return;
  }

  // Set key for mail. @todo: use $transition->isScheduled() instead?  Or use a Factory.
  $key = '';
  $key = ($trigger == 'on_state_change') ? 'workflow_notification_on_state_change_mail_trigger' : $key;
  $key = ($trigger == 'before_state_change') ? 'workflow_notification_before_state_change_mail_trigger' : $key;

  foreach ($notifications as $id => $notification) {
    /** @var WorkflowNotification $notifications */
    $roles = $notification->roles;
    $tkn_rpl_val = _workflow_notifications_token_replace($notification->mail_ids, $notification->message['value'], $notification->subject, $entity, $transition);
    $mail_ids = _workflow_notifications_get_value_as_array($tkn_rpl_val['mail_ids']);
    $to = _workflow_notifications_collect_mail_ids($roles, $mail_ids);
    $params['subject'] = $tkn_rpl_val['subject'];
    $params['message'] = $tkn_rpl_val['message'];
    _workflow_notifications_mail_send($to, $params, $key);
  }
}

/**
 * send mail to all users.
 * @param $start_time
 * @param $end_time
 * @param $notification
 */
function _workflow_notifications_send_mail_to_all($start_time, $end_time, $notification) {
  workflow_debug('', __FUNCTION__, __LINE__);

  // @todo: use WorkflowScheduledTransition::loadBetween();
  $query_publish = \Drupal::database()->select('workflow_transition_schedule', 'ws')->fields('ws');
  $query_publish->condition('ws.timestamp', [$start_time, $end_time], 'BETWEEN');
  $query_publish->condition('ws.from_sid', $notification->from_sid, '=');
  if ($notification->to_sid != 'any') {
    $query_publish->condition('ws.to_sid', $notification->to_sid, '=');
  }
  $result_publish = $query_publish->execute()->fetchAll();

  $key = 'workflow_notification_before_mail_trigger';
  foreach ($result_publish as $row => $val) {
    $entity = entity_load($val->entity_type, $val->entity_id);
    $field = _workflow_info_fields($entity, $val->entity_type);
    $fieldName = $field[key($field)]->getName();
    // @todo: next line has no effect.
    $transition = WorkflowScheduledTransition::loadByProperties($val->entity_type, $val->entity_id, [], $fieldName);
    $roles = $notification->roles;
    $tkn_rpl_val = _workflow_notifications_token_replace($notification->mail_ids, $notification->message['value'], $notification->subject, $entity, $transition);
    $mail_ids = _workflow_notifications_get_value_as_array($tkn_rpl_val['mail_ids']);
    $to = _workflow_notifications_collect_mail_ids($roles, $mail_ids);
    $params['subject'] = $tkn_rpl_val['subject'];
    $params['message'] = $tkn_rpl_val['message'];
    _workflow_notifications_mail_send($to, $params, $key);
  }
}

/**
 * returns array from string.
 * @param $value
 * @return array
 */
function _workflow_notifications_get_value_as_array($value) {
  $values = "\r\n" . $value;
  $result = array_filter(preg_split('/\r\n|[\r\n]/', $values));
  return $result;
}

/**
 * Implements token replace.
 */
function _workflow_notifications_token_replace($mail_ids, $message, $subject, $entity, $transition) {
  $token_service = \Drupal::token();
  $tkn_rpl_val = [];
  $tkn_rpl_val['mail_ids'] = $token_service->replace($mail_ids, ['comment' => $entity, 'node' => $entity, 'term' => $entity, 'media' => $entity, 'paragraph' => $entity, 'workflow_transition' => $transition, 'workflow_scheduled_transition' => $transition]);
  $tkn_rpl_val['message'] = $token_service->replace($message, ['comment' => $entity, 'node' => $entity, 'term' => $entity, 'media' => $entity, 'paragraph' => $entity, 'workflow_transition' => $transition, 'workflow_scheduled_transition' => $transition]);
  $tkn_rpl_val['subject'] = $token_service->replace($subject, ['comment' => $entity, 'node' => $entity, 'term' => $entity, 'media' => $entity, 'paragraph' => $entity, 'workflow_transition' => $transition, 'workflow_scheduled_transition' => $transition]);
  return $tkn_rpl_val;
}

/**
 * Get all mail adresses.
 *
 * Add the role-defined adresses t the user-specified adresses.
 */
function _workflow_notifications_collect_mail_ids($roles, $mail_ids) {

  if ($roles) {
    foreach ($roles as $role_id => $role) {
      if ($role == '0') {
        continue;
      }

      // @todo: the selection upon role is not working.
      $ids = \Drupal::entityQuery('user')
        ->condition('status', 1)
        ->condition('roles', $role)
        ->execute();
//      $group = $query->orConditionGroup()
//        ->condition('roles', 'managers')
//        ->condition('roles', 'administrator');
//      $ids = $query->condition($group)->execute();

      $user_storage = \Drupal::service('entity_type.manager')->getStorage('user');
      $ids = $user_storage->getQuery()
        ->condition('status', 1)
 // @todo       ->condition('roles', $role, 'IN')
        ->execute();

      $users = $user_storage->loadMultiple($ids);
//      $users = \Drupal\user\Entity\User::loadMultiple($ids);

      foreach ($users as $key => $user) {
        $mail_ids[] = $user->getEmail();
      }
    }
  }

  $mail_ids = array_unique($mail_ids);
  return $mail_ids;
}

/**
 * send mail.
 */
function _workflow_notifications_mail_send($to, $params, $key) {
  $mailManager = \Drupal::service('plugin.manager.mail');
  $langcode = \Drupal::currentUser()->getPreferredLangcode();
  $send = true;
  $module = 'workflow_notifications'; // @todo: use DEFINE CONSTANT.
  $to = implode(', ', $to);
  $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
  if ($result['result'] !== true) {
    \Drupal::logger('workflow-mail-log')->error("There was a problem sending your message and it was not sent.");
    drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
  }
  else {
    \Drupal::logger('workflow-mail-log')->notice("Email sent successfully to " . $to);
    drupal_set_message(t('Email sent successfully.'));
  }
}
